### ISSUE TITLE
Jenkins is broken

### ISSUE THREAD

**Issue by cdietrich** [eclipse-xtext/xtext#3272]
https://ci.eclipse.org/xtext/job/xtext/job/main/1678/console

**Comment by cdietrich** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5362

**Comment by cdietrich** [comment]
maybe related https://www.eclipse.org/lists/cross-project-issues-dev/msg19990.html

**Comment by cdietrich** [comment]
we might also need a replacement for
https://github.com/eclipse-xtext/xtext-website/blob/main/Jenkinsfile
:(

or have something different how we generate the page

**Comment by cdietrich** [comment]
> We put a workaround in place that the current configurations still work with the deprecated centos-8-6b name, but this should be changed to ubuntu-2404-6gb in all build configurations (where applicable). As mentioned in the cross-project's mailing list post, please fix any references to outdated CentOS images and point to the Ubuntu images instead.

**Comment by LorenzoBettini** [comment]
@cdietrich with my additional commit https://github.com/eclipse-xtext/xtext/commit/db19ce2d1801ed209f4d9367d642fb6ff06125af the build has started:

https://ci.eclipse.org/xtext/job/xtext/job/cd-try-ubuntu-2024/2/console

**Comment by cdietrich** [comment]
I assume we need different ones for different jobs eg in xtext and mwe

**Comment by LorenzoBettini** [comment]
but it immediately failed :'(

Maybe Xvnc is not there?

**Comment by LorenzoBettini** [comment]
I'm also scared by:

```
+ echo 'Available memory: 512M'
Available memory: 512M
```

**Comment by cdietrich** [comment]
This is why I really hope for a migration guide by @fredericgurr

**Comment by LorenzoBettini** [comment]
However, I see this is working https://ci.eclipse.org/xtext/job/xtext/job/main/1686/consoleFull

`Started by user [Frederic Gurr](https://ci.eclipse.org/xtext/user/frederic.gurr@eclipse-foundation.org)`

so maybe they fixed upstream?

**Comment by LorenzoBettini** [comment]
Also this one https://ci.eclipse.org/xtext/job/xtext/job/cd-more-scms/2/console is running fine

**Comment by LorenzoBettini** [comment]
However, jobs in Jenkins don't seem to start automatically anymore; I mean after something is pushed on GitHub...

**Comment by cdietrich** [comment]
maybe this is still related to the move?
@eclipse-xtext/eclipsefdn-releng do you have an idea?

**Comment by fredg02** [comment]
Maybe, but I have to fix other things before looking into this particular problem.

**Comment by fredg02** [comment]
https://ci.eclipse.org/xtext/job/xtext/ was still referencing the old GitHub repo at https://github.com/eclipse/xtext. I fixed that for this build. You will need to adjust this for any other job that points to the old repo URLs.

Furthermore, in the new GH org, the webhook was missing. That's fixed as well. So builds for the xtext multi-branch job should get triggered again.

**Comment by cdietrich** [comment]
Is there a better way of fixing this besides stepping through all jobs manually

**Comment by fredg02** [comment]
Everything can be automated, it's just software, right? :)

It depends on your setup/project structure. You could create a new item called "Organization Folder" to automatically scan for Multibranch pipeline builds in all repos of your GH org. In that case, you only have to set the org once.

If you use a different build structure, most likely, going through all jobs manually is the only way. Since we are not planning to move repos to a different GH org anytime soon, this should be a one-time thing. 

You could use this as an opportunity to clean up or remove old jobs (some of them have not been run in years). Committers and release engineers will appreciate it.

**Comment by cdietrich** [comment]
so you have an idea whats the problem with
https://ci.eclipse.org/xtext/job/releng/job/website-deploy/1113/console

**Comment by cdietrich** [comment]
https://ci.eclipse.org/xtext/job/lsp4j/3892/console
also seems to have problems

**Comment by fredg02** [comment]
> https://ci.eclipse.org/xtext/job/lsp4j/3892/console
> also seems to have problems

Typo: https://ci.eclipse.org/xtext/job/lsp4j/jobConfigHistory/showDiffFiles?timestamp1=2024-11-29_13-41-56&timestamp2=2024-11-29_14-41-13

**Comment by fredg02** [comment]
> so you have an idea whats the problem with https://ci.eclipse.org/xtext/job/releng/job/website-deploy/1113/console
> 
> maybe just waiting works

See https://github.com/eclipse-xtext/xtext-website/pull/74

**Comment by cdietrich** [comment]
```
./xtext/releng/jenkins/cleanup-project-storage/Jenkinsfile:      inheritFrom 'centos-8'
./xtext/releng/jenkins/check-versions/Jenkinsfile:      inheritFrom 'centos-8' // this job is dead. propose to drop the script
./xtext/Jenkinsfile:      inheritFrom 'centos-8-6gb'
```

**Comment by cdietrich** [comment]
https://ci.eclipse.org/xtext/job/xtext-monorepo-full-deploy-nightly/412/

oomed

@fredg02 is this due to the agent any?
@LorenzoBettini do you know why we dont do a inheritfrom there?

**Comment by fredg02** [comment]
Build #411 was successful with `agent any` 4 hours ago, so I don't see a connection.

**Comment by LorenzoBettini** [comment]
> https://ci.eclipse.org/xtext/job/xtext-monorepo-full-deploy-nightly/412/
> 
> oomed
> 
> @fredg02 is this due to the agent any? @LorenzoBettini do you know why we dont do a inheritfrom there?

I think it was done like that before the repo merge.

It says 4gb memory and I think that should be enough if we don't run tests.

Maybe just a hiccup?

**Comment by HannesWell** [comment]
Is this resolved now? Jenkins seem to work fine nowadays.

**Comment by cdietrich** [comment]
we see the war job still fail now and then
e.g. this one 3 weeks ago
https://ci.eclipse.org/xtext/job/xtext-monorepo-full-deploy-nightly/602/console
